{{- if not .Values.secrets.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "relayfile.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "relayfile.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.internalHmacSecret }}
  RELAYFILE_INTERNAL_HMAC_SECRET: {{ .Values.secrets.internalHmacSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.productionDsn }}
  RELAYFILE_PRODUCTION_DSN: {{ .Values.secrets.productionDsn | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  RELAYFILE_JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
  {{- if .Values.providers.notion.token }}
  RELAYFILE_NOTION_TOKEN: {{ .Values.providers.notion.token | quote }}
  {{- end }}
{{- end }}
